aws:
  ses:
    access-key: ${SES_ACCESS_KEY}
    secret-key: ${SES_SECRET_KEY}
  s3:
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    bucket: ${S3_BUCKET}

---

spring:
  config:
    activate:
      on-profile: local
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


---
spring:
  config:
    activate:
      on-profile: dev
  redis:
    host: ${DEV_REDIS_HOST:localhost}
    port: ${DEV_REDIS_PORT:6379}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true