spring:
  profiles:
    active:
    include:
      - domain

---
spring:
  config:
    activate:
      on-profile: test

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: dev



---
spring:
  config:
    activate:
      on-profile: prod