spring:
  profiles:
    active: local
    include:
      - domain
      - infra

logging:
  config: classpath:logback-${spring.profiles.active}.xml
---
spring:
  config:
    activate:
      on-profile: test

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: dev



---
spring:
  config:
    activate:
      on-profile: prod