name: eatcook batch cron

on:
  schedule:
    - cron: '0 * * * *'

env:
  ACTIVE_PROFILE: "dev"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out The Repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle Clean & Build
        run: ./gradlew :itcook-batch:build

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./itcook-batch
          push: true
          args: --build-arg PROFILE=$ACTIVE_PROFILE
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/itcook-batch-dev:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: EC2 Docker Run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_DEV_HOST }}
          username: ${{ secrets.EC2_DEV_USER }}
          password: ${{ secrets.EC2_DEV_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd app
            sudo touch .env
            echo "${{ secrets.ENV_VARS }}" | sudo tee .env > /dev/null
            docker rm $(docker ps -a -q --filter "status=exited")
            docker image prune -a -f
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/itcook-batch-dev:latest
            docker run -d --env-file .env ${{ secrets.DOCKERHUB_USERNAME }}/itcook-batch-dev:latest
